/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - An odxml42 Tool
    This file will not be overwritten by default!
*************************************************/
using System;
using System.ComponentModel;
                        
namespace YesAndOST.Lib.DataClasses
{                   
    
    public partial class Avatar 
    {
        public Avatar()
        {
            this.InitPoco();
        }

        public override string ToString()
        {
            return this.Handle;
        }
    }
}